name: routing
intents:
    greeting: greeting
    cancel: cancel
    upgrade: upgrade
states:
    greeting:
        flow: greeting
        return: true
    cancel:
        flow: cancel
        return: true
    upgrade:
        flow: upgrade
        return: true
