name: routing
route: true
states:
    greeting:
        flow: greeting
        return: true
    cancel:
        flow: cancel
        return: true
    upgrade:
        flow: upgrade
        return: true
